# Generated by Django 3.1.6 on 2021-02-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMovies', '0002_auto_20210204_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
