# Generated by Django 3.1.6 on 2021-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMovies', '0003_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='movie',
            name='premiere',
            field=models.DateField(blank=True, null=True),
        ),
    ]
