# Generated by Django 3.1.6 on 2021-02-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMovies', '0004_auto_20210204_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('genre', models.PositiveSmallIntegerField(choices=[(8, 'Historical'), (4, 'Crime'), (3, 'Comedy'), (5, 'Drama'), (11, 'Science Fiction'), (0, 'Other'), (9, 'Horror'), (1, 'Action'), (6, 'Experimental'), (10, 'Romance'), (7, 'Fantasy'), (12, 'Thriller'), (13, 'Wester'), (2, 'Animation')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='additional_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebMovies.additionalinfo'),
        ),
    ]
